"""
Sample sex and phasing.
"""
import os
import pandas as pd
def hap_score_gb(df):
    df = df.droplevel(0)
    return abs(df.loc["0"] - df.loc["1"])/abs(df.loc["0"]+df.loc["1"])
def get_chrom_hap_score(dump_dir):
    """
    Get chrom_hap_score of samples.
    Input:
        dump_dir: rd/dump generated by hires_utils
    Output:
        pd.Series
    """
    res = pd.concat((pd.read_pickle(file) for file in [os.path.join(dump_dir, i) for i in os.listdir(dump_dir)]),axis=1)
    res.columns = [i.split("_")[0] for i in os.listdir(dump_dir)]

    dfs = {}
    for index, df in res.groupby(level=0):
        dfs[index] = hap_score_gb(df)
    chrom_hap_score = pd.DataFrame(dfs).mean(axis=1)
    return chrom_hap_score