"""
Sample sex and phasing.
"""
import os
import pandas as pd
from .calculate import mt
from .hicio import parse_seg
from .genome import GenomeIdeograph

def hap_score_gb(df):
    df = df.droplevel(0)
    return abs(df.loc["0"] - df.loc["1"])/abs(df.loc["0"]+df.loc["1"])
def get_chrom_hap_score(dump_dir):
    """
    Get chrom_hap_score of samples.
    Input:
        dump_dir: rd/dump generated by hires_utils
    Output:
        pd.Series
    """
    res = pd.concat((pd.read_pickle(file) for file in [os.path.join(dump_dir, i) for i in os.listdir(dump_dir)]),axis=1)
    res.columns = [i.split("_")[0] for i in os.listdir(dump_dir)]

    dfs = {}
    for index, df in res.groupby(level=0):
        dfs[index] = hap_score_gb(df)
    chrom_hap_score = pd.DataFrame(dfs).mean(axis=1)
    return chrom_hap_score

def count_chrom_phased(filename:str, *args)->pd.Series:
    """
    Count number of phased (with separable SNP) segments per chromosome from a .seg.gz file.
    Input:
        filename: Path to the .seg.gz file.
    Output:
        A pandas Series with multi-index (chromosome, phasing) and counts.
    """
    #print(f"Processing file: {filename}")
    df = parse_seg(filename)
    cp_count = df.value_counts(["chrom","phase"])
    return cp_count
@mt(
    "hic_basic.phasing"
)
def mt_count_chrom_phased(filename:str)->pd.Series:
    pass

def count_phased_seg_perbin(filename, genome="mm10",binsize=1e6):
    """
    Count the number of phased segments per bin of a given genome.
    Input:
        filename: str, path to the .seg file
        genome: str, genome name (default: "mm10")
        binsize: int, size of the bins (default: 1e6)
    Output:
        pandas DataFrame with columns: "chrom", "start", "phase", "count"
    """
    genome = GenomeIdeograph(genome)
    # --- read in the .seg file --- #
    df = parse_seg(filename)

    # --- transform to pairs format to fit append_bins method --- #
    fake_pairs = pd.DataFrame(
        {
            "chr1" : df["chrom"],
            "pos1" : df["start"],
            "chr2" : df["chrom"],
            "pos2" : df["end"],
            "phase0" : df["phase"],
            "phase1" : df["phase"],
        }
    ).assign(
        readID = ".",
        strand1 = "+",
        strand2 = "+"
    )

    fake_pairs = genome.append_bins(
        fake_pairs,
        binsize=binsize,
    )

    phase_bin_counts = fake_pairs.groupby(
        ["chrom1", "start1", "phase0"]
    ).size().reset_index(name="count")
    phase_bin_counts.columns = ["chrom", "start", "phase", "count"]
    phase_bin_counts = phase_bin_counts.set_index(["chrom", "start", "phase"])["count"]
    return phase_bin_counts